#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : parameter-framework
Version  : 3.2.8
Release  : 15
URL      : https://github.com/intel/parameter-framework/archive/v3.2.8.tar.gz
Source0  : https://github.com/intel/parameter-framework/archive/v3.2.8.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: parameter-framework-bin
Requires: parameter-framework-python3
Requires: parameter-framework-data
Requires: parameter-framework-license
Requires: parameter-framework-python
BuildRequires : asio-dev
BuildRequires : buildreq-cmake
BuildRequires : catch2-dev
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : python3
Patch1: 0001-Disable-Werror.patch

%description
# parameter-framework
[![Build Status](https://travis-ci.org/01org/parameter-framework.svg?branch=master)](https://travis-ci.org/01org/parameter-framework)
[![Windows Build Status](https://ci.appveyor.com/api/projects/status/ga24jp8tet0qimbu/branch/master)](https://ci.appveyor.com/project/parameter-framework/parameter-framework)
[![Coverage Status](https://codecov.io/github/01org/parameter-framework/coverage.svg?branch=master)](https://codecov.io/github/01org/parameter-framework?branch=master)

%package bin
Summary: bin components for the parameter-framework package.
Group: Binaries
Requires: parameter-framework-data
Requires: parameter-framework-license

%description bin
bin components for the parameter-framework package.


%package data
Summary: data components for the parameter-framework package.
Group: Data

%description data
data components for the parameter-framework package.


%package dev
Summary: dev components for the parameter-framework package.
Group: Development
Requires: parameter-framework-bin
Requires: parameter-framework-data
Provides: parameter-framework-devel

%description dev
dev components for the parameter-framework package.


%package license
Summary: license components for the parameter-framework package.
Group: Default

%description license
license components for the parameter-framework package.


%package python
Summary: python components for the parameter-framework package.
Group: Default
Requires: parameter-framework-python3

%description python
python components for the parameter-framework package.


%package python3
Summary: python3 components for the parameter-framework package.
Group: Default
Requires: python3-core

%description python3
python3 components for the parameter-framework package.


%prep
%setup -q -n parameter-framework-3.2.8
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533069838
mkdir clr-build
pushd clr-build
%cmake .. -DCMAKE_INCLUDE_PATH=/usr/include/catch -DPYTHON_BINDINGS=OFF -DBUILD_TESTING=OFF -DFATAL_WARNINGS:BOOL=OFF
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1533069838
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/parameter-framework
cp COPYING.txt %{buildroot}/usr/share/doc/parameter-framework/COPYING.txt
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/EddParser.py
/usr/bin/PFWScriptGenerator.py
/usr/bin/PfwBaseTranslator.py
/usr/bin/domainGenerator.py
/usr/bin/domainGenerator.sh
/usr/bin/domainGeneratorConnector
/usr/bin/hostConfig.py
/usr/bin/lightRoutingUpdate.sh
/usr/bin/pfClientSimulator.py
/usr/bin/remote-process
/usr/bin/test-platform
/usr/bin/updateRoutageDomains.sh
/usr/bin/xmlValidator.py

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/remote-process
/usr/share/parameter-framework/schemas/ComponentLibrary.xsd
/usr/share/parameter-framework/schemas/ComponentTypeSet.xsd
/usr/share/parameter-framework/schemas/ConfigurableDomain.xsd
/usr/share/parameter-framework/schemas/ConfigurableDomains.xsd
/usr/share/parameter-framework/schemas/FileIncluder.xsd
/usr/share/parameter-framework/schemas/Parameter.xsd
/usr/share/parameter-framework/schemas/ParameterFrameworkConfiguration.xsd
/usr/share/parameter-framework/schemas/ParameterSettings.xsd
/usr/share/parameter-framework/schemas/Subsystem.xsd
/usr/share/parameter-framework/schemas/SystemClass.xsd
/usr/share/parameter-framework/schemas/W3cXmlAttributes.xsd

%files dev
%defattr(-,root,root,-)
/usr/include/parameter/c/ParameterFramework.h
/usr/include/parameter/c/cparameter_export.h
/usr/include/parameter/client/CommandHandlerInterface.h
/usr/include/parameter/client/ElementHandle.h
/usr/include/parameter/client/ParameterHandle.h
/usr/include/parameter/client/ParameterMgrFullConnector.h
/usr/include/parameter/client/ParameterMgrLoggerForward.h
/usr/include/parameter/client/ParameterMgrPlatformConnector.h
/usr/include/parameter/client/SelectionCriterionInterface.h
/usr/include/parameter/client/SelectionCriterionTypeInterface.h
/usr/include/parameter/client/parameter_export.h
/usr/include/parameter/plugin/BitParameterBlockType.h
/usr/include/parameter/plugin/ConfigurableElement.h
/usr/include/parameter/plugin/DefaultElementLibrary.h
/usr/include/parameter/plugin/Element.h
/usr/include/parameter/plugin/ElementBuilder.h
/usr/include/parameter/plugin/ElementLibrary.h
/usr/include/parameter/plugin/FormattedSubsystemObject.h
/usr/include/parameter/plugin/InstanceConfigurableElement.h
/usr/include/parameter/plugin/LoggingElementBuilderTemplate.h
/usr/include/parameter/plugin/Mapper.h
/usr/include/parameter/plugin/MappingContext.h
/usr/include/parameter/plugin/ParameterBlockType.h
/usr/include/parameter/plugin/ParameterType.h
/usr/include/parameter/plugin/PathNavigator.h
/usr/include/parameter/plugin/Plugin.h
/usr/include/parameter/plugin/Subsystem.h
/usr/include/parameter/plugin/SubsystemLibrary.h
/usr/include/parameter/plugin/SubsystemObject.h
/usr/include/parameter/plugin/SubsystemObjectCreator.h
/usr/include/parameter/plugin/SubsystemObjectFactory.h
/usr/include/parameter/plugin/Syncer.h
/usr/include/parameter/plugin/TypeElement.h
/usr/include/parameter/plugin/VirtualSubsystem.h
/usr/include/parameter/plugin/log/Context.h
/usr/include/parameter/plugin/log/ILogger.h
/usr/include/parameter/plugin/log/LogWrapper.h
/usr/include/parameter/plugin/log/Logger.h
/usr/include/parameter/plugin/parameter_export.h
/usr/include/parameter/utility/ErrorContext.hpp
/usr/include/parameter/utility/NonCopyable.hpp
/usr/include/parameter/utility/Utility.h
/usr/include/parameter/utility/convert.hpp
/usr/include/parameter/xmlserializer/XmlElement.h
/usr/include/parameter/xmlserializer/XmlSerializingContext.h
/usr/include/parameter/xmlserializer/XmlSink.h
/usr/include/parameter/xmlserializer/XmlSource.h
/usr/lib/cmake/ParameterFramework/ParameterFrameworkConfig.cmake
/usr/lib/cmake/ParameterFramework/ParameterFrameworkConfigVersion.cmake
/usr/lib/cmake/ParameterFramework/ParameterFrameworkTargets-relwithdebinfo.cmake
/usr/lib/cmake/ParameterFramework/ParameterFrameworkTargets.cmake
/usr/lib/libcparameter.so
/usr/lib/libparameter.so
/usr/lib/libremote-processor.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/parameter-framework/COPYING.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
